# Generated by Django 5.0.6 on 2024-05-14 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_intro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=4)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_intro_app.student')),
            ],
        ),
    ]
