# Generated by Django 5.0.6 on 2024-05-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_intro_app', '0003_instructor_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Instructor',
            new_name='instructor',
        ),
    ]
