# Generated by Django 5.0.6 on 2024-05-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_intro_app', '0004_rename_instructor_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='django_intro_app.course'),
        ),
    ]
